Repository RadioAstronomySoftwareGroup/pyuvdata, pull requests merged in 2019-08, with the labels that each got.

#646 new minor version
  CHANGELOG.md
  pyuvdata/VERSION
Labels: packaging

#660 Fix some test syntax issues
  pyuvdata/tests/test_uvbeam.py
  pyuvdata/tests/test_uvcal.py
  pyuvdata/tests/test_uvdata.py
Labels: bug

#657 Fill out docstring for checkWarnings
  pyuvdata/tests/__init__.py
Labels: docs

#664 Fix a couple capitalization typos
  docs/make_flag_parameters.py
  pyuvdata/tests/test_uvflag.py
  pyuvdata/uvflag.py
Labels: uvflag
