Repository RadioAstronomySoftwareGroup/pyuvdata, pull requests merged in 2020-07, with the labels that each got.

#872 calfits.py now writes an appropriate BITPIX value of -64 to .calfits …
  pyuvdata/uvcal/calfits.py
Labels: Calibration

#874 remove macosx forced ncurses update in install_conda.sh
  ci/install_conda.sh
Labels: continuous_integration

#877 Update the changelog for version 2.1
  CHANGELOG.md
Labels: packaging

#879 Clean up our gitignore
  .gitignore
Labels: packaging
