Repository RadioAstronomySoftwareGroup/pyuvdata, pull requests merged in 2020-03, with the labels that each got.

#794 reinstate conda updates in conda install script
  ci/install_conda.sh
Labels: continuous_integration

#793 Make new minor release
  CHANGELOG.md
Labels: packaging

#795 remove test alias because setup.py tests is deprecated
  setup.cfg
Labels: technical debt
