Repository RadioAstronomySoftwareGroup/pyuvdata, pull requests merged in 2020-06, with the labels that each got.

#861 Fix a few documentation issues
  README.md
  pyuvdata/uvdata/uvdata.py
Labels: docs

#859 Make sure all tests are run in CI on Windows
  .github/workflows/macosx_windows_ci.yaml
  setup.py
Labels: continuous_integration

#860 Improve UVParameter equality method for Quantity types
  pyuvdata/parameter.py
  pyuvdata/tests/test_parameter.py
Labels: enhancement

#869 Make changes for numpy v1.19
  pyuvdata/uvdata/miriad.py
  pyuvdata/uvdata/uvh5.py
Labels: UVData, bug
