Repository RadioAstronomySoftwareGroup/pyuvdata, pull requests merged in 2021-12, with the labels that each got.

#1113 Testing if yaml change allows github tests to pass
  .github/workflows/macosx_windows_ci.yaml
Labels: continuous_integration

#1116 Fix a bug in write_calfits when time_range is None
  CHANGELOG.md
  pyuvdata/uvcal/calfits.py
  pyuvdata/uvcal/tests/test_calfits.py
Labels: bug, Calibration

#1120 update the changelog for v2.2.5
  CHANGELOG.md
Labels: packaging
