Repository RadioAstronomySoftwareGroup/pyuvdata, pull requests merged in 2023-02, with the labels that each got.

#1260 Minor fix to MIR unit testing
  pyuvdata/uvdata/tests/test_mir_parser.py
Labels: bug, UVData

#1264 Use importlib.metadata rather than pkg_resources
  pyuvdata/__init__.py
Labels: warning, technical debt

#1257 Add external tests for pyradiosky and pyuvsim
  ci/azure-piplines.yml
Labels: continuous_integration
