Repository RadioAstronomySoftwareGroup/pyuvdata, pull requests merged in 2024-02, with the labels that each got.

#1393 Fix so that write_uvfits doesn't change the object, add loopback testing
  pyuvdata/uvdata/tests/test_uvfits.py
  pyuvdata/uvdata/uvfits.py
Labels: bug, UVData

#1394 Add a changelog entry for small UVFlag bug fixed in a recent PR
  CHANGELOG.md
Labels: bug, docs

#1395 Pre-commit tweak
  setup.cfg
Labels: technical debt, continuous_integration

#1405 Adding support for initializing `MirParser` from `Path` objects
  CHANGELOG.md
  pyuvdata/uvdata/mir_meta_data.py
  pyuvdata/uvdata/mir_parser.py
  pyuvdata/uvdata/tests/test_mir_parser.py
Labels: UVData, SMA

#1402 ignore warnings in hera_cal and hera_qm test runs
  ci/azure-piplines.yml
Labels: continuous_integration

#1406 Prepare for v2.4.2
  CHANGELOG.md
Labels: packaging
